### PR TITLE
chore: deprecation note added

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Review by lholmquist — COMMENTED** [review]
I think we need to point to the images that are replacing these

**Comment by helio-frota** [comment]
Ok, I think the github repo is https://github.com/sclorg/s2i-nodejs-container
And we can add the links to RHCC ubi8/nodejs-10.

**Comment by lholmquist** [comment]
the link to the RHCC image is https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/ubi8/nodejs-10

**Comment by helio-frota** [comment]
link added, I'm going to merge :+1:

**Pull request merged**
